# Project : Customers Loan Risk Identification Model

# About the Dataset

This dataset describes customers loan details. The aim of this project is to  preprocess customers loan data. Being a Data Analyst, i am doing data gathering, cleaning the data and preprocess the data.

# Installing the Packages

In [1]:
# To perfrom the mathematical functions, importing the Numpy packages
import numpy as np

In [2]:
#The set_printoptions() function is used to set printing options.

#These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

# Importing the Dataset

In [3]:
# Importing the txt files data.
data_raw = np.genfromtxt("Customers-Loan-Risk.csv",delimiter = ';',autostrip = True,skip_header =1)
data_raw

array([[65676913.  ,         nan,    15000.  , ...,         nan,         nan,      447.57],
       [63177012.  ,         nan,    11250.  , ...,         nan,         nan,      738.9 ],
       [41021489.  ,         nan,    16400.  , ...,         nan,         nan,     3789.71],
       ...,
       [38507183.  ,         nan,    22500.  , ...,         nan,         nan,     7903.32],
       [46644700.  ,         nan,    17325.  , ...,         nan,         nan,     3940.3 ],
       [38171566.  ,         nan,     6250.  , ...,         nan,         nan,         nan]])

# Checking Missing Values

In [4]:
# Checking the missing values in element wise and returns the number of True values(1s) in the array.
np.isnan(data_raw).sum()

88005

In [5]:
# Obtaining the maximum value of an array along the axis ,ignoring any Nan value.
missing_data_fill = np.nanmax(data_raw) + 1
missing_data_fill

68616520.0

In [6]:
# Obtainging the mean value of an array ignoring the NaN value without effecting NaN value.
missing data_mean = np.nanmean(data_raw, axis = 0)
missing data_mean

<ipython-input-6-d61b19c63903>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [8]:
#Obtaining the min value of an array ignoring the NaN value
np.nanmin(data_raw,axis =0)

<ipython-input-8-65db00e0e14a>:2: RuntimeWarning: All-NaN slice encountered
  np.nanmin(raw_data_np,axis =0)


array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
             nan,       nan,       nan,       nan,       nan,      0.  ])

In [9]:
missing_data_stats = np.array([np.nanmin(data_raw, axis = 0),
                           missing data_mean,
                           np.nanmax(data_raw, axis =0)])
missing_data_stats

<ipython-input-9-56bb8248ccf5>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
<ipython-input-9-56bb8248ccf5>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis =0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Customizing the columns

In [10]:
missing data_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [11]:
(missing data_mean).squeeze()

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [13]:
# Obtaining the indices of array elements that are non-zero.
# Obtaining  tests element-wise, whether it is NaN or not, returns the result as a boolean array.
# Removing one-dimensional entry from the shape of the given array
columns_strings = np.argwhere(np.isnan(missing data_mean)).squeeze()
columns_numeric = np.argwhere(np.isnan(missing data_mean) == False).squeeze()


In [14]:
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [15]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Verifying the Data

In [16]:
customers_data_strings = np.genfromtxt("Customers-Loan-Risk.csv",
                                   delimiter = ';',
                                   skip_header = 1,
                                   autostrip = True,
                                   usecols = columns_strings,
                                   dtype = np.str)
customers_data_strings

<ipython-input-16-408aad9e9a59>:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['Nov-15', 'Current', '', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=65676913', 'NY'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=63177012', 'TX'],
       ['Mar-15', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=41021489', 'OR'],
       ...,
       ['Jan-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38507183', 'AZ'],
       ['May-15', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46644700', 'GA'],
       ['Jan-15', 'Current', '36 months', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38171566', 'CA']],
      dtype='<U69')

In [18]:
customers_data_numeric = np.genfromtxt("Customers-Loan-Risk.csv",
                                   delimiter = ';',
                                   autostrip = True,
                                   skip_header = 1,
                                   usecols = columns_numeric,
                                   filling_values = missing_data_fill)
customers_data_numeric

array([[65676913.  ,    15000.  ,    15000.  , 68616520.  ,      457.97,      447.57],
       [63177012.  ,    11250.  ,    11250.  , 68616520.  ,      377.38,      738.9 ],
       [41021489.  ,    16400.  ,    16400.  , 68616520.  ,      381.52,     3789.71],
       ...,
       [38507183.  ,    22500.  ,    22500.  , 68616520.  ,      720.64,     7903.32],
       [46644700.  ,    17325.  ,    17325.  ,       23.99,      498.31,     3940.3 ],
       [38171566.  ,     6250.  ,     6250.  , 68616520.  ,      203.12, 68616520.  ]])

# Column Headers

In [20]:
data_raw

array([[65676913.  ,         nan,    15000.  , ...,         nan,         nan,      447.57],
       [63177012.  ,         nan,    11250.  , ...,         nan,         nan,      738.9 ],
       [41021489.  ,         nan,    16400.  , ...,         nan,         nan,     3789.71],
       ...,
       [38507183.  ,         nan,    22500.  , ...,         nan,         nan,     7903.32],
       [46644700.  ,         nan,    17325.  , ...,         nan,         nan,     3940.3 ],
       [38171566.  ,         nan,     6250.  , ...,         nan,         nan,         nan]])

In [22]:
# Obtaining the shape of the array
data_raw.shape

(10000, 14)

In [23]:
column_header = np.genfromtxt("Customers-Loan-Risk.csv",
                             delimiter = ';',
                             autostrip = True,
                             skip_footer = data_raw.shape[0],
                             dtype = np.str)
column_header

<ipython-input-23-4503a671bd8d>:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [25]:
column_header[columns_numeric]

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [26]:
column_header[columns_strings]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
#Mapping the header_full columns 
column_header_strings,column_header_numeric = column_header[columns_strings],column_header[columns_numeric]

In [28]:
column_header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [29]:
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Checkpoint Dataset:

In [30]:
# Creating Checkpoint
def checkpoint(file_name,checkpoint_header, checkpoint_data):
    np.savez(file_name,header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [31]:
# Checkpoint created
checkpoint_test = checkpoint("checkpoint-test",column_header_strings,customers_data_strings)

In [32]:
# Tessting the checkpoint data
checkpoint_test['data']

array([['Nov-15', 'Current', '', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=65676913', 'NY'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=63177012', 'TX'],
       ['Mar-15', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=41021489', 'OR'],
       ...,
       ['Jan-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38507183', 'AZ'],
       ['May-15', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46644700', 'GA'],
       ['Jan-15', 'Current', '36 months', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38171566', 'CA']],
      dtype='<U69')

In [33]:
#  Verifying the checkpoint data
np.array_equal(checkpoint_test['data'],customers_data_strings)

True

# Column Strings

In [34]:
column_header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
column_header_strings[0] = "issue_date"

In [36]:
column_header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

# Issue Date

In [37]:
#For each element in self, return a copy with the leading and trailing characters removed.
customers_data_strings[:,0] =np.chararray.strip(customers_data_strings[:,0], "-15")
customers_data_strings

array([['Nov', 'Current', '', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=65676913', 'NY'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=63177012', 'TX'],
       ['Mar', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=41021489', 'OR'],
       ...,
       ['Jan', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38507183', 'AZ'],
       ['May', 'Current', '60 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46644700', 'GA'],
       ['Jan', 'Current', '36 months', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38171566', 'CA']],
      dtype='<U69')

In [39]:
# Obtaining the unique values in the array
np.unique(customers_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [40]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [41]:
# With the forloop,mapping the months with numbers in string format.
for i in range(13):
    customers_data_strings[:,0]= np.where(customers_data_strings[:,0] == months[i],
                                    i,customers_data_strings[:,0])

In [42]:
np.unique(customers_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

# Loan Status

In [43]:
# Identifying the unique values
np.unique(customers_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [44]:
# Verifying the size of the array
np.unique(customers_data_strings[:,1]).size

9

In [45]:
# Creating new array with the specified strings in column
columns_ignore = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [46]:
# we can see that one array having values are checked in a different numpy array having different elements with different sizes.
np.isin(customers_data_strings[:,1],columns_ignore)

array([False, False, False, ..., False, False, False])

In [48]:
# Passing conditions
customers_data_strings[:,1] = np.where(np.isin(customers_data_strings[:,1],columns_ignore),0,1)

In [49]:
np.unique(customers_data_strings[:,1])

array(['0', '1'], dtype='<U69')

# Term

In [50]:
customers_data_strings[:,2] = np.chararray.strip(customers_data_strings[:,2]," months")
customers_data_strings[:,2]

array(['', '36', '60', ..., '36', '60', '36'], dtype='<U69')

In [52]:
column_header_strings[2] = "term_months"

In [53]:
customers_data_strings[:,2] = np.where(customers_data_strings[:,2] == '',
                                 '60',
                                 customers_data_strings[:,2])
customers_data_strings[:,2]

array(['60', '36', '60', ..., '36', '60', '36'], dtype='<U69')

In [56]:
np.unique(customers_data_strings[:,2])

array(['36', '60'], dtype='<U69')

# Grade and Subgrade

In [57]:
np.unique(customers_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [58]:
np.unique(customers_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [59]:
for i in np.unique(customers_data_strings[:,3])[1:]:
    customers_data_strings[:,4] = np.where((customers_data_strings[:,4] == '') & (customers_data_strings[:,3] == i),
                                      i + '5',
                                      customers_data_strings[:,4])

In [60]:
customers_data_strings[:,4] = np.where(customers_data_strings[:,4] == '',
                                  'H1',
                                  customers_data_strings[:,4])

In [61]:
np.unique(customers_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [62]:
#Deleting the unnecessary columns
customers_data_strings = np.delete(customers_data_strings,3,axis=1)
customers_data_strings

array([['11', '1', '60', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=65676913', 'NY'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=63177012', 'TX'],
       ['3', '1', '60', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=41021489', 'OR'],
       ...,
       ['1', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38507183', 'AZ'],
       ['5', '1', '60', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46644700', 'GA'],
       ['1', '1', '36', ..., 'Not Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=38171566', 'CA']],
      dtype='<U69')

In [63]:
column_header_strings = np.delete(column_header_strings,3)

In [64]:
column_header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [65]:
# Creating dictionary with keys and values
keys = list(np.unique(customers_data_strings[:,3]))                         
values = list(range(1, np.unique(customers_data_strings[:,3]).shape[0] + 1)) 
new_subgrade = dict(zip(keys, values))

In [66]:
new_subgrade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [67]:
for i in np.unique(customers_data_strings[:,3]):
        customers_data_strings[:,3] = np.where(customers_data_strings[:,3] == i, 
                                          new_subgrade[i],
                                          customers_data_strings[:,3])

In [68]:
np.unique(customers_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [70]:
np.unique(customers_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [71]:
customers_data_strings[:,4] == 'Not Verified'

array([ True, False, False, ..., False, False,  True])

In [72]:
customers_data_strings[:,4] = np.where((customers_data_strings[:,4] == '') | (customers_data_strings[:,4] == 'Not Verified'), 0, 1)

In [74]:
np.unique(customers_data_strings[:,4])

array(['0', '1'], dtype='<U69')

# URL

In [75]:
customers_data_strings[:,5] = np.chararray.strip(customers_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [77]:
customers_data_numeric[:,0].astype(dtype = np.int32)

array([65676913, 63177012, 41021489, ..., 38507183, 46644700, 38171566])

In [78]:
customers_data_strings[:,5].astype(dtype = np.int32)

array([65676913, 63177012, 41021489, ..., 38507183, 46644700, 38171566])

In [79]:
customers_data_strings[:,5]

array(['65676913', '63177012', '41021489', ..., '38507183', '46644700', '38171566'], dtype='<U69')

In [80]:
np.array_equal(customers_data_numeric[:,0].astype(dtype = np.int32), customers_data_strings[:,5].astype(dtype = np.int32))

True

In [81]:
customers_data_strings

array([['11', '1', '60', ..., '0', '65676913', 'NY'],
       ['0', '1', '36', ..., '1', '63177012', 'TX'],
       ['3', '1', '60', ..., '1', '41021489', 'OR'],
       ...,
       ['1', '1', '36', ..., '1', '38507183', 'AZ'],
       ['5', '1', '60', ..., '1', '46644700', 'GA'],
       ['1', '1', '36', ..., '0', '38171566', 'CA']], dtype='<U69')

In [84]:
customers_data_strings[:,5]

array(['NY', 'TX', 'OR', ..., 'AZ', 'GA', 'CA'], dtype='<U69')

In [85]:
column_header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [86]:
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# State Address

In [87]:
column_header_strings[5] = "state_address"

In [88]:
states_names, states_count = np.unique(customers_data_strings[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [89]:
customers_data_strings[:,5] = np.where(customers_data_strings[:,5] == '', 
                                  0, 
                                  customers_data_strings[:,5])

In [90]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [91]:
customers_data_strings[:,5] = np.where(np.isin(customers_data_strings[:,5], states_west), 1, customers_data_strings[:,5])
customers_data_strings[:,5] = np.where(np.isin(customers_data_strings[:,5], states_south), 2, customers_data_strings[:,5])
customers_data_strings[:,5] = np.where(np.isin(customers_data_strings[:,5], states_midwest), 3, customers_data_strings[:,5])
customers_data_strings[:,5] = np.where(np.isin(customers_data_strings[:,5], states_east), 4, customers_data_strings[:,5])

In [92]:
np.unique(customers_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [93]:
customers_data_strings = customers_data_strings.astype(np.int)
customers_data_strings


<ipython-input-93-6460139559fc>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = loan_data_strings.astype(np.int)


array([[11,  1, 60,  2,  0,  4],
       [ 0,  1, 36, 12,  1,  2],
       [ 3,  1, 60, 14,  1,  1],
       ...,
       [ 1,  1, 36,  7,  1,  1],
       [ 5,  1, 60, 27,  1,  2],
       [ 1,  1, 36,  8,  0,  1]])

# Strings Checkpoint

In [95]:
checkpoint_strings = checkpoint("Checkpoint-Strings", column_header_strings, customers_data_strings)

In [96]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [97]:
checkpoint_strings["data"]

array([[11,  1, 60,  2,  0,  4],
       [ 0,  1, 36, 12,  1,  2],
       [ 3,  1, 60, 14,  1,  1],
       ...,
       [ 1,  1, 36,  7,  1,  1],
       [ 5,  1, 60, 27,  1,  2],
       [ 1,  1, 36,  8,  0,  1]])

In [98]:
np.array_equal(checkpoint_strings['data'], customers_data_strings)

True

# Column Numeric

In [99]:
np.isnan(customers_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [100]:
np.isnan(customers_data_numeric).sum()

0

# ID

In [101]:
missing_data_fill

68616520.0

In [102]:
np.isin(customers_data_numeric[:,0], missing_data_fill)

array([False, False, False, ..., False, False, False])

In [103]:
np.isin(customers_data_numeric[:,0], missing_data_fill).sum()

0

In [104]:
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Temporary Stats

In [105]:
missing_data_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# Funded Amount

In [107]:
ustomers_data_numeric[:,2] = np.where(customers_data_numeric[:,2] == missing_data_fill, 
                                  missing_data_stats[0, columns_numeric[2]],
                                  customers_data_numeric[:,2])
customers_data_numeric[:,2]

array([15000., 11250., 16400., ..., 22500., 17325.,  6250.])

In [109]:
for i in [1,3,4,5]:
    customers_data_numeric[:,i] = np.where(customers_data_numeric[:,i] == missing_data_fill,
                                      missing_data_stats[2, columns_numeric[i]],
                                      customers_data_numeric[:,i])

# The Exchange Rate

In [110]:
USD_INR = np.genfromtxt("USD-INR.csv", delimiter = ',', autostrip = True, skip_header = 1)
USD_INR

array([[74.81, 74.93, 74.68, 74.87,  0.  ],
       [75.12, 75.15, 74.75, 74.81,  0.  ],
       [75.24, 75.25, 74.88, 75.12,  0.  ],
       [75.01, 75.53, 75.03, 75.24,  0.  ],
       [75.03, 75.03, 75.03, 75.03,  0.  ],
       [75.03, 75.03, 75.03, 75.03,  0.  ],
       [75.  , 75.29, 74.88, 75.03,  0.  ],
       [75.31, 75.37, 74.88, 75.  ,  0.  ],
       [75.5 , 75.55, 75.17, 75.31,  0.  ],
       [75.4 , 75.77, 75.16, 75.48,  0.  ],
       [75.13, 75.54, 75.06, 75.4 ,  0.  ],
       [75.31, 75.31, 75.13, 75.31,  0.  ],
       [75.13, 75.31, 75.13, 75.13,  0.  ],
       [74.83, 75.31, 72.82, 75.31,  0.  ],
       [74.77, 75.02, 74.69, 74.83,  0.  ],
       [74.56, 75.07, 74.54, 74.77,  0.  ],
       [74.57, 74.8 , 74.41, 74.56,  0.  ],
       [74.15, 74.61, 74.12, 74.57,  0.  ],
       [74.15, 74.15, 74.14, 74.15,  0.  ],
       [74.14, 74.14, 74.14, 74.14,  0.  ],
       [74.25, 74.41, 74.07, 74.14,  0.  ]])

In [111]:
USD_INR = np.genfromtxt("USD-INR.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
USD_INR

array([74.87, 74.81, 75.12, 75.24, 75.03, 75.03, 75.03, 75.  , 75.31, 75.48, 75.4 , 75.31, 75.13,
       75.31, 74.83, 74.77, 74.56, 74.57, 74.15, 74.14, 74.14])

In [112]:
exchange_rate = customers_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             USD_INR[i-1],
                             exchange_rate)    

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(USD_INR),
                         exchange_rate)

exchange_rate

array([75.4 , 74.92, 75.12, ..., 74.87, 75.03, 74.87])

In [113]:
customers_data_numeric.shape

(10000, 6)

In [114]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [115]:
exchange_rate

array([[75.4 ],
       [74.92],
       [75.12],
       ...,
       [74.87],
       [75.03],
       [74.87]])

In [117]:
customers_data_numeric

array([[65676913.  ,    15000.  ,    15000.  ,       28.99,      457.97,      447.57],
       [63177012.  ,    11250.  ,    11250.  ,       28.99,      377.38,      738.9 ],
       [41021489.  ,    16400.  ,    16400.  ,       28.99,      381.52,     3789.71],
       ...,
       [38507183.  ,    22500.  ,    22500.  ,       28.99,      720.64,     7903.32],
       [46644700.  ,    17325.  ,    17325.  ,       23.99,      498.31,     3940.3 ],
       [38171566.  ,     6250.  ,     6250.  ,       28.99,      203.12,    41913.62]])

In [119]:
#stack the sequence of input arrays horizontally
np.hstack((customers_data_numeric, exchange_rate))

array([[65676913.  ,    15000.  ,    15000.  , ...,      457.97,      447.57,       75.4 ],
       [63177012.  ,    11250.  ,    11250.  , ...,      377.38,      738.9 ,       74.92],
       [41021489.  ,    16400.  ,    16400.  , ...,      381.52,     3789.71,       75.12],
       ...,
       [38507183.  ,    22500.  ,    22500.  , ...,      720.64,     7903.32,       74.87],
       [46644700.  ,    17325.  ,    17325.  , ...,      498.31,     3940.3 ,       75.03],
       [38171566.  ,     6250.  ,     6250.  , ...,      203.12,    41913.62,       74.87]])

In [121]:
customers_data_numeric = np.hstack((customers_data_numeric, exchange_rate))

In [122]:
#Added the new column
column_header_numeric = np.concatenate((column_header_numeric, np.array(['exchange_rate'])))
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [123]:
np.savetxt("Customers_Loan_header_numeric_1.csv",
            column_header_numeric,
            fmt = "%s",
            delimiter = ',')

# Conversion USD to INR

In [124]:
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [125]:
columns_dollar = np.array([1,2,4,5])

In [126]:
customers_data_numeric[:,6]

array([75.4 , 74.92, 75.12, ..., 74.87, 75.03, 74.87])

In [127]:
for i in columns_dollar:
    customers_data_numeric = np.hstack((customers_data_numeric, np.reshape(customers_data_numeric[:,i] / customers_data_numeric[:,6], (10000,1))))

In [128]:
customers_data_numeric.shape

(10000, 11)

In [129]:
customers_data_numeric

array([[65676913.  ,    15000.  ,    15000.  , ...,      198.93,        6.07,        5.94],
       [63177012.  ,    11250.  ,    11250.  , ...,      150.17,        5.04,        9.86],
       [41021489.  ,    16400.  ,    16400.  , ...,      218.32,        5.08,       50.45],
       ...,
       [38507183.  ,    22500.  ,    22500.  , ...,      300.54,        9.63,      105.57],
       [46644700.  ,    17325.  ,    17325.  , ...,      230.89,        6.64,       52.51],
       [38171566.  ,     6250.  ,     6250.  , ...,       83.48,        2.71,      559.85]])

# Modifying Headers

In [131]:
cloumn_header_additional = np.array([column_name + '_INR' for column_name in column_header_numeric[columns_dollar]])
cloumn_header_additional

array(['loan_amnt_INR', 'funded_amnt_INR', 'installment_INR', 'total_pymnt_INR'], dtype='<U15')

In [132]:
column_header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [133]:
column_header_numeric[columns_dollar]=np.array([column_name + '_USD' for column_name in column_header_numeric[columns_dollar]])
column_header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate'], dtype='<U19')

In [134]:
column_header_numeric = np.concatenate((column_header_numeric, cloumn_header_additional))
column_header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_INR', 'funded_amnt_INR', 'installment_INR', 'total_pymnt_INR'],
      dtype='<U19')

In [135]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [136]:
column_header_numeric = column_header_numeric[columns_index_order]
column_header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_INR', 'funded_amnt_USD', 'funded_amnt_INR', 'int_rate',
       'installment_USD', 'installment_INR', 'total_pymnt_USD', 'total_pymnt_INR', 'exchange_rate'],
      dtype='<U19')

In [137]:
customers_data_numeric = customers_data_numeric[:,columns_index_order]

# Interest Rate

In [139]:
customers_data_numeric[:,5]

array([28.99, 28.99, 28.99, ..., 28.99, 23.99, 28.99])

In [140]:
customers_data_numeric[:,5] = customers_data_numeric[:,5]/100
customers_data_numeric[:,5]

array([0.29, 0.29, 0.29, ..., 0.29, 0.24, 0.29])

In [141]:
customers_data_numeric_interest_rate = customers_data_numeric[:,5]

# Numeric Checkpoint

In [142]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", column_header_numeric, customers_data_numeric)

In [143]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_INR', 'funded_amnt_USD', 'funded_amnt_INR', 'int_rate',
        'installment_USD', 'installment_INR', 'total_pymnt_USD', 'total_pymnt_INR', 'exchange_rate'],
       dtype='<U19'),
 array([[65676913.  ,    15000.  ,      198.93, ...,      447.57,        5.94,       75.4 ],
        [63177012.  ,    11250.  ,      150.17, ...,      738.9 ,        9.86,       74.92],
        [41021489.  ,    16400.  ,      218.32, ...,     3789.71,       50.45,       75.12],
        ...,
        [38507183.  ,    22500.  ,      300.54, ...,     7903.32,      105.57,       74.87],
        [46644700.  ,    17325.  ,      230.89, ...,     3940.3 ,       52.51,       75.03],
        [38171566.  ,     6250.  ,       83.48, ...,    41913.62,      559.85,       74.87]]))

# New Dataset

In [144]:
checkpoint_strings['data'].shape

(10000, 6)

In [145]:
checkpoint_numeric['data'].shape

(10000, 11)

In [146]:
customer_new_dataset = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))
customer_new_dataset

array([[65676913.  ,    15000.  ,      198.93, ...,        2.  ,        0.  ,        4.  ],
       [63177012.  ,    11250.  ,      150.17, ...,       12.  ,        1.  ,        2.  ],
       [41021489.  ,    16400.  ,      218.32, ...,       14.  ,        1.  ,        1.  ],
       ...,
       [38507183.  ,    22500.  ,      300.54, ...,        7.  ,        1.  ,        1.  ],
       [46644700.  ,    17325.  ,      230.89, ...,       27.  ,        1.  ,        2.  ],
       [38171566.  ,     6250.  ,       83.48, ...,        8.  ,        0.  ,        1.  ]])

In [148]:
np.isnan(customer_new_dataset).sum()

0

In [149]:
column_header = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))
column_header

array(['id', 'loan_amnt_USD', 'loan_amnt_INR', 'funded_amnt_USD', 'funded_amnt_INR', 'int_rate',
       'installment_USD', 'installment_INR', 'total_pymnt_USD', 'total_pymnt_INR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

# Sorting New Dataset

In [151]:
customer_new_dataset = customer_new_dataset[np.argsort(customer_new_dataset[:,0])]
customer_new_dataset

array([[  373332.  ,     9950.  ,      131.82, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,      158.97, ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,      133.67, ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,       74.36, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,       53.12, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,      286.83, ...,        3.  ,        0.  ,        2.  ]])

In [152]:
np.argsort(customer_new_dataset[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

# Storing the New Dataset

In [154]:
#
customer_new_dataset = np.vstack((column_header,customer_new_dataset))
customer_new_dataset

array([['id', 'loan_amnt_USD', 'loan_amnt_INR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '131.81575204860889', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '158.97377131490518', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '74.3632151732829', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '53.11658226663064', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '286.82954423980544', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [156]:
column_header

array(['id', 'loan_amnt_USD', 'loan_amnt_INR', 'funded_amnt_USD', 'funded_amnt_INR', 'int_rate',
       'installment_USD', 'installment_INR', 'total_pymnt_USD', 'total_pymnt_INR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')